/*
 * HIP test for V_ADD_I16, V_SUB_I16, and V_SUB_I32 (VOP3A integer ALU).
 *
 * All three instructions use the 64-bit VOP3A encoding, which is distinct
 * from the 32-bit VOP2 encoding used for ordinary integer arithmetic:
 *
 *   v_add_u32_e32 / v_sub_u32_e32  ← VOP2, generated by plain C int arithmetic
 *   v_add_i16 / v_sub_i16          ← VOP3A, 16-bit signed lanes
 *   v_sub_i32                      ← VOP3A, 32-bit signed subtract
 *
 * The VOP3A encoding is selected when the compiler needs the 64-bit
 * instruction word (e.g. for a third source, OPSEL bits, ABS/NEG
 * modifiers, or an SGPR source), or when the operand type is explicitly
 * 16-bit.  Simple C arithmetic on int16_t and int32_t variables generates
 * the VOP2 forms instead, so inline assembly is used here to force the
 * VOP3A forms.
 *
 * Semantics (from the ISA and gem5 vop3.cc):
 *
 *   v_add_i16  VDST, SRC0, SRC1   D.i16 = S0.i16 + S1.i16
 *   v_sub_i16  VDST, SRC0, SRC1   D.i16 = S0.i16 - S1.i16
 *   v_sub_i32  VDST, SRC0, SRC1   D.i32 = S0.i32 - S1.i32
 *
 * All three wrap on overflow (no saturation unless the CLAMP bit is set,
 * which none of these kernels use).  ABS and NEG modifiers are not
 * supported; the gem5 execute() functions assert their absence.
 *
 * Build:
 *   hipcc -O2 -o i16_i32_integer_ops i16_i32_integer_ops.cpp
 *
 * Run in gem5:
 *   gem5.opt config.py -- ./i16_i32_integer_ops
 */

#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

#define GPU_CHECK(cmd)                                                      \
    do {                                                                    \
        hipError_t e = (cmd);                                               \
        if (e != hipSuccess) {                                              \
            fprintf(stderr, "HIP error %s:%d '%s'\n", __FILE__, __LINE__,  \
                    hipGetErrorString(e));                                   \
            exit(1);                                                        \
        }                                                                   \
    } while (0)

static const int N          = 256;
static const int BLOCK_SIZE = 64;

/*
 * Kernel A: v_add_i16  VDST, SRC0, SRC1
 *
 * D.i16 = S0.i16 + S1.i16  (wraps on overflow; no carry out)
 *
 * The "v" constraint allocates a VGPR for each 16-bit operand.  The
 * compiler extends int16_t to 32 bits in the VGPR but only the low 16
 * bits are consumed and written by the instruction.
 */
__global__ void
kernel_add_i16(const int16_t *a, const int16_t *b, int16_t *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= n)
        return;

    int16_t va = a[i], vb = b[i], vd;

    __asm__ volatile(
        "v_add_i16 %0, %1, %2\n\t"
        : "=v"(vd)
        : "v"(va), "v"(vb));

    out[i] = vd;
}

/*
 * Kernel B: v_sub_i16  VDST, SRC0, SRC1
 *
 * D.i16 = S0.i16 - S1.i16  (wraps on overflow)
 */
__global__ void
kernel_sub_i16(const int16_t *a, const int16_t *b, int16_t *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= n)
        return;

    int16_t va = a[i], vb = b[i], vd;

    __asm__ volatile(
        "v_sub_i16 %0, %1, %2\n\t"
        : "=v"(vd)
        : "v"(va), "v"(vb));

    out[i] = vd;
}

/*
 * Kernel C: v_sub_i32  VDST, SRC0, SRC1
 *
 * D.i32 = S0.i32 - S1.i32  (wraps on overflow; no borrow out)
 *
 * This is the VOP3A form of 32-bit subtraction.  The ISA manual notes
 * that its overflow / condition-code behaviour differs from the SOP2
 * S_SUB_I32; this kernel does not inspect any condition codes.
 */
__global__ void
kernel_sub_i32(const int32_t *a, const int32_t *b, int32_t *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= n)
        return;

    int32_t va = a[i], vb = b[i], vd;

    __asm__ volatile(
        "v_sub_i32 %0, %1, %2\n\t"
        : "=v"(vd)
        : "v"(va), "v"(vb));

    out[i] = vd;
}

int
main(void)
{
    /* ----- host buffers ----- */
    int16_t *h_a16  = (int16_t *)malloc(N * sizeof(int16_t));
    int16_t *h_b16  = (int16_t *)malloc(N * sizeof(int16_t));
    int32_t *h_a32  = (int32_t *)malloc(N * sizeof(int32_t));
    int32_t *h_b32  = (int32_t *)malloc(N * sizeof(int32_t));
    int16_t *h_add16 = (int16_t *)malloc(N * sizeof(int16_t));
    int16_t *h_sub16 = (int16_t *)malloc(N * sizeof(int16_t));
    int32_t *h_sub32 = (int32_t *)malloc(N * sizeof(int32_t));

    /*
     * Use a mix of positive, negative, and boundary values so that signed
     * semantics (two's-complement wrap) are exercised and distinguishable
     * from unsigned arithmetic.
     */
    for (int i = 0; i < N; i++) {
        /* 16-bit: span the signed range, including values near INT16_MIN/MAX */
        h_a16[i] = (int16_t)((i - N / 2) * 128);   /* -16384 .. +16256 */
        h_b16[i] = (int16_t)((i % 32 - 16) * 512);  /* -8192  .. +7680  */

        /* 32-bit: large magnitudes to show wrap on overflow */
        h_a32[i] = (int32_t)((i - N / 2) * (1 << 20)); /* ~±134M */
        h_b32[i] = (int32_t)((i % 64 - 32) * (1 << 22)); /* ~±134M */
    }

    /* ----- device buffers ----- */
    int16_t *d_a16, *d_b16, *d_add16, *d_sub16;
    int32_t *d_a32, *d_b32, *d_sub32;

    GPU_CHECK(hipMalloc(&d_a16,   N * sizeof(int16_t)));
    GPU_CHECK(hipMalloc(&d_b16,   N * sizeof(int16_t)));
    GPU_CHECK(hipMalloc(&d_add16, N * sizeof(int16_t)));
    GPU_CHECK(hipMalloc(&d_sub16, N * sizeof(int16_t)));
    GPU_CHECK(hipMalloc(&d_a32,   N * sizeof(int32_t)));
    GPU_CHECK(hipMalloc(&d_b32,   N * sizeof(int32_t)));
    GPU_CHECK(hipMalloc(&d_sub32, N * sizeof(int32_t)));

    GPU_CHECK(hipMemcpy(d_a16, h_a16, N * sizeof(int16_t), hipMemcpyHostToDevice));
    GPU_CHECK(hipMemcpy(d_b16, h_b16, N * sizeof(int16_t), hipMemcpyHostToDevice));
    GPU_CHECK(hipMemcpy(d_a32, h_a32, N * sizeof(int32_t), hipMemcpyHostToDevice));
    GPU_CHECK(hipMemcpy(d_b32, h_b32, N * sizeof(int32_t), hipMemcpyHostToDevice));

    /* ----- launch ----- */
    int grid = N / BLOCK_SIZE;

    hipLaunchKernelGGL(kernel_add_i16, dim3(grid), dim3(BLOCK_SIZE), 0, 0,
                       d_a16, d_b16, d_add16, N);
    GPU_CHECK(hipGetLastError());

    hipLaunchKernelGGL(kernel_sub_i16, dim3(grid), dim3(BLOCK_SIZE), 0, 0,
                       d_a16, d_b16, d_sub16, N);
    GPU_CHECK(hipGetLastError());

    hipLaunchKernelGGL(kernel_sub_i32, dim3(grid), dim3(BLOCK_SIZE), 0, 0,
                       d_a32, d_b32, d_sub32, N);
    GPU_CHECK(hipGetLastError());
    GPU_CHECK(hipDeviceSynchronize());

    /* ----- copy back ----- */
    GPU_CHECK(hipMemcpy(h_add16, d_add16, N * sizeof(int16_t), hipMemcpyDeviceToHost));
    GPU_CHECK(hipMemcpy(h_sub16, d_sub16, N * sizeof(int16_t), hipMemcpyDeviceToHost));
    GPU_CHECK(hipMemcpy(h_sub32, d_sub32, N * sizeof(int32_t), hipMemcpyDeviceToHost));

    /* ----- verify ----- */
    int pass = 1;
    for (int i = 0; i < N; i++) {
        /* v_add_i16: two's-complement 16-bit add with wrap */
        int16_t exp_add16 = (int16_t)(h_a16[i] + h_b16[i]);
        if (h_add16[i] != exp_add16) {
            fprintf(stderr, "FAIL v_add_i16[%d]: got %d expected %d "
                    "(a=%d b=%d)\n", i, h_add16[i], exp_add16,
                    h_a16[i], h_b16[i]);
            pass = 0; break;
        }

        /* v_sub_i16: two's-complement 16-bit subtract with wrap */
        int16_t exp_sub16 = (int16_t)(h_a16[i] - h_b16[i]);
        if (h_sub16[i] != exp_sub16) {
            fprintf(stderr, "FAIL v_sub_i16[%d]: got %d expected %d "
                    "(a=%d b=%d)\n", i, h_sub16[i], exp_sub16,
                    h_a16[i], h_b16[i]);
            pass = 0; break;
        }

        /* v_sub_i32: two's-complement 32-bit subtract with wrap */
        int32_t exp_sub32 = h_a32[i] - h_b32[i];
        if (h_sub32[i] != exp_sub32) {
            fprintf(stderr, "FAIL v_sub_i32[%d]: got %d expected %d "
                    "(a=%d b=%d)\n", i, h_sub32[i], exp_sub32,
                    h_a32[i], h_b32[i]);
            pass = 0; break;
        }
    }

    if (pass) {
        printf("v_add_i16: out[0]=%d  out[%d]=%d\n",
               h_add16[0], N - 1, h_add16[N - 1]);
        printf("v_sub_i16: out[0]=%d  out[%d]=%d\n",
               h_sub16[0], N - 1, h_sub16[N - 1]);
        printf("v_sub_i32: out[0]=%d  out[%d]=%d\n",
               h_sub32[0], N - 1, h_sub32[N - 1]);
    }
    printf("%s\n", pass ? "PASSED" : "FAILED");

    /* ----- cleanup ----- */
    GPU_CHECK(hipFree(d_a16));   GPU_CHECK(hipFree(d_b16));
    GPU_CHECK(hipFree(d_add16)); GPU_CHECK(hipFree(d_sub16));
    GPU_CHECK(hipFree(d_a32));   GPU_CHECK(hipFree(d_b32));
    GPU_CHECK(hipFree(d_sub32));
    free(h_a16); free(h_b16); free(h_a32); free(h_b32);
    free(h_add16); free(h_sub16); free(h_sub32);

    return pass ? 0 : 1;
}
